baseURL: "https://manitapote.github.io" 
title: Manita Pote
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Books
          url: books/
          weight: 5 
        - name: Papers
          url: papers/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        - name: Data
          url: data/
          weight: 4 
        - name: Blog
          url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
          weight: 6

params:
    description: "This website hosts Manita Pote's research papers, blogs, projects, curriculum vitae, and contact information."
    author: Manita Pote
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["news", "blogs","projects","papers"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Manita Pote
          subtitle: "I am a PhD candidate in Informatics at Indiana University, Bloomington. My research investigates the mechanisms behind manipulation in online information spaces, leveraging behavioral data alongside methods from network science, machine learning, and statistical modeling. I am driven by the challenge of transforming large-scale, complex behavioral signals into meaningful insights, bridging the rigor of academic inquiry with the demands of real-world impact."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Latest News
              url: news/
            - name: Papers
              url: papers/
            - name: Projects
              url: projects/
            - name: Blogs
              url: blogs/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/

    socialIcons:
        - name: CV
          url: https://drive.google.com/file/d/1RFaivWQLTy31dpLcd2VOvoZ28K3kxe_a/view?usp=sharing
        - name: Email
          url: manitapote@gmail.com
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=ukS-vPcAAAAJ&hl=en&oi=ao
        - name: GitHub
          url: https://github.com/manitapote
        - name: Twitter
          url: https://x.com/manitapote
     
    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Manita Pote"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
